# Site info
title: "みなゆろぐ"
description: >-
  電子工作とかITとか
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:categories/:title:output_ext
url: "https://blog.m7u.net" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/logo.png
favicon: /assets/logo.png

# Author info
author:
  name        : "みなぎ"
  bio         : "強いおたくになりたい。"
  email       : ""
  github      : "minagi-yu"
  atcoder     : "minagi"
  twitter     : "minagi_yu"
  misskey:
    instance  : "misskey.io"
    username  : "minagi"
  pronamafc   : "201"
  atcoder     : "minagi"

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Pagination options
#paginate: 5
#paginate_path: "/page:num/"

# Localization
lang: ja
timezone: Asia/Tokyo

# Sass options
sass:
  style: expanded

# Feed
# feed:
#   path: /atom.xml

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-paginate

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE